name: Test Self-Hosted (No Downloads)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [self-hosted, win10]

    steps:
      - name: Basic info
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          "Runner: $env:RUNNER_NAME"
          "OS: $env:RUNNER_OS"
          "Arch: $env:RUNNER_ARCH"
          hostname
          whoami
          Get-Date

      - name: Checkout
        uses: actions/checkout@v4

      - name: Disk + Network
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          Get-PSDrive -PSProvider FileSystem | Format-Table -AutoSize
          ipconfig
