name: Test Self-hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, win10]
    steps:
      - name: Show system
        shell: pwsh
        run: |
          hostname
          whoami
          Get-Date
          ipconfig
      - name: Show disk
        shell: pwsh
        run: |
          Get-PSDrive -PSProvider FileSystem | Format-Table -AutoSize
